// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: shipping.proto

package shippingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipRequest) Reset() {
	*x = ShipRequest{}
	mi := &file_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipRequest) ProtoMessage() {}

func (x *ShipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipRequest.ProtoReflect.Descriptor instead.
func (*ShipRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *ShipRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ShipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShippingId    string                 `protobuf:"bytes,1,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipResponse) Reset() {
	*x = ShipResponse{}
	mi := &file_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipResponse) ProtoMessage() {}

func (x *ShipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipResponse.ProtoReflect.Descriptor instead.
func (*ShipResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *ShipResponse) GetShippingId() string {
	if x != nil {
		return x.ShippingId
	}
	return ""
}

func (x *ShipResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelShipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShippingId    string                 `protobuf:"bytes,1,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShipRequest) Reset() {
	*x = CancelShipRequest{}
	mi := &file_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShipRequest) ProtoMessage() {}

func (x *CancelShipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShipRequest.ProtoReflect.Descriptor instead.
func (*CancelShipRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *CancelShipRequest) GetShippingId() string {
	if x != nil {
		return x.ShippingId
	}
	return ""
}

type CancelShipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShipResponse) Reset() {
	*x = CancelShipResponse{}
	mi := &file_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShipResponse) ProtoMessage() {}

func (x *CancelShipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShipResponse.ProtoReflect.Descriptor instead.
func (*CancelShipResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *CancelShipResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_shipping_proto protoreflect.FileDescriptor

const file_shipping_proto_rawDesc = "" +
	"\n" +
	"\x0eshipping.proto\x12\n" +
	"shippingpb\"'\n" +
	"\vShipRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"G\n" +
	"\fShipResponse\x12\x1f\n" +
	"\vshipping_id\x18\x01 \x01(\tR\n" +
	"shippingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"4\n" +
	"\x11CancelShipRequest\x12\x1f\n" +
	"\vshipping_id\x18\x01 \x01(\tR\n" +
	"shippingId\",\n" +
	"\x12CancelShipResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9d\x01\n" +
	"\x0fShippingService\x129\n" +
	"\x04Ship\x12\x17.shippingpb.ShipRequest\x1a\x18.shippingpb.ShipResponse\x12O\n" +
	"\x0eCancelShipping\x12\x1d.shippingpb.CancelShipRequest\x1a\x1e.shippingpb.CancelShipResponseB\x17Z\x15backend/pb/shippingpbb\x06proto3"

var (
	file_shipping_proto_rawDescOnce sync.Once
	file_shipping_proto_rawDescData []byte
)

func file_shipping_proto_rawDescGZIP() []byte {
	file_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)))
	})
	return file_shipping_proto_rawDescData
}

var file_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shipping_proto_goTypes = []any{
	(*ShipRequest)(nil),        // 0: shippingpb.ShipRequest
	(*ShipResponse)(nil),       // 1: shippingpb.ShipResponse
	(*CancelShipRequest)(nil),  // 2: shippingpb.CancelShipRequest
	(*CancelShipResponse)(nil), // 3: shippingpb.CancelShipResponse
}
var file_shipping_proto_depIdxs = []int32{
	0, // 0: shippingpb.ShippingService.Ship:input_type -> shippingpb.ShipRequest
	2, // 1: shippingpb.ShippingService.CancelShipping:input_type -> shippingpb.CancelShipRequest
	1, // 2: shippingpb.ShippingService.Ship:output_type -> shippingpb.ShipResponse
	3, // 3: shippingpb.ShippingService.CancelShipping:output_type -> shippingpb.CancelShipResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_proto_init() }
func file_shipping_proto_init() {
	if File_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_proto_msgTypes,
	}.Build()
	File_shipping_proto = out.File
	file_shipping_proto_goTypes = nil
	file_shipping_proto_depIdxs = nil
}
